### ISSUE TITLE
Console has errors like 'Error using matlab.unittest.internal.mustContainCharacters (line 13) Invalid 'file' value. Input must contain one or more characters.  Error in matlab.unittest.internal.fileResolver (line 9) mustContainCharacters(file,'file');'

### ISSUE THREAD

**Issue by SangaviJayagopi** [mathworks/jenkins-matlab-plugin#168]
Reproduction steps:

1. Fork this repo https://github.com/mathworks/ci-test-repo 
2. Create a pipeline project using Jenkins configuration
3. Running the pipeline project causes error messages 

Error using matlab.unittest.internal.mustContainCharacters (line 13)
Invalid 'file' value. Input must contain one or more characters.

Error in matlab.unittest.internal.fileResolver (line 9)
mustContainCharacters(file,'file');

Error in matlab.unittest.internal.fileinformation.FileInformation.forFile (line 42)
            fullName = fileResolver(filename);

Error in matlab.unittest.internal.coverage.MATLABSource>getFileInformationFromFiles (line 27)
    fileInfoCell{idx} = FileInformation.forFile(files{idx});

Error in matlab.unittest.internal.coverage.MATLABSource/produceFileInformation (line 15)
                fileInfoCell{idx} = getFileInformationFromFiles(files);

Error in matlab.unittest.internal.services.coverage.MATLABCoberturaPublishingService/publish (line 17)
            fileInformationArray = theSources.produceFileInformation;

Error in matlab.unittest.internal.services.coverage.CoberturaPublishingService/fulfill (line 21)
                    services(serviceIndex).publish(fileName,sources,profileData);

Error in matlab.unittest.plugins.codecoverage.CoberturaFormat/generateCoverageReport (line 60)
           fulfill(coveragePublishingServices,coberturaFormat.Filename,sources,profileData);

Error in matlab.unittest.plugins.CodeCoveragePlugin/afterRun (line 271)
                format.generateCoverageReport(plugin.Sources,profileData);

Error in matlab.unittest.plugins.CodeCoveragePlugin>@()plugin.afterRun(pluginData) (line 279)
            finishup = onCleanup(@() plugin.afterRun(pluginData));

Error in onCleanup/delete (line 80)
            obj.task();

Error in matlab.unittest.plugins.CodeCoveragePlugin/runSession (line 281)
        end

Error in matlab.unittest.plugins.TestRunnerPlugin/invokeTestContentOperatorMethod_ (line 760)
                [varargout{1:nargout}] = method(plugin, pluginData);

Error in matlab.unittest.TestRunner/evaluateMethodOnPlugins (line 437)
            [varargout{1:nargout}] = iter.CurrentOperator.invokeTestContentOperatorMethod_(method, pluginData, iter);

Error in matlab.unittest.TestRunner/evaluateMethodOnPluginsFromMethodName (line 425)
            runner.evaluateMethodOnPlugins(str2func(method),pluginData);

Error in matlab.unittest.TestRunner/doRunWithFcn (line 408)
            runner.evaluateMethodOnPluginsFromMethodName(runFcn,pluginData);

Error in matlab.unittest.TestRunner/run (line 296)
            result = doRunWithFcn(runner,'runSession', pluginData);

Error in tempscript_2caa (line 28)
results = runner.run(suite);

Error in scriptgen.Script/run (line 60)
                evalin('caller', strcat(scriptName, ';'));

Error in test_runner_ef118fb1_00cf_4828_960d_d8685ed45ac3 (line 6)
run(testScript);] 
[>In tempscript_2caa (line 28)
In scriptgen/Script/run (line 60)
In test_runner_ef118fb1_00cf_4828_960d_d8685ed45ac3 (line 6)]
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS

**Comment by nbhoski** [comment]
Can you please provide the pipeline script you used to run this and MATLAB version ?

**Comment by SangaviJayagopi** [comment]
This is the pipeline script I tried to use in jenkins: (Refer https://github.com/mathworks/ci-test-repo)

pipeline {
   agent any
   environment {
      PATH="/Applications/MATLAB_R2019a.app:$PATH"
   }
   tools {
       matlab 'MATLABR2019a'
       matlab 'MATLABR2020b'
   }
 
    stages{
     
      
       stage('Run MATLAB Tests'){
            steps
            {
               runMATLABTests(
                               sourceFolder: ["/Users/sjayagop/Desktop/src","/Users/sjayagop/Desktop/test"],
                               testResultsTAP: 'new-results/results.tap',
                               testResultsJUnit: 'new-results/results.xml',
                               codeCoverageCobertura: 'new-coverage/coverage.xml',
                               modelCoverageCobertura: 'new-coverage/coverage.xml')
            }  
        }
    }        
    
}

**Comment by nbhoski** [comment]
Cant reproduce it locally  i am seeing below which is expected 

Started by user admin
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] node
Running on Jenkins in C:\Users\nbhoski\.jenkins\workspace\pipeline_test
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Run MATLAB Tests)
[Pipeline] runMATLABTests
[pipeline_test] $ cmd.exe /C C:\Users\nbhoski\AppData\Local\Temp\cf15df1b-c29a-48fe-9dfa-365585f35248\run_matlab_command.bat '"addpath('C:\Users\nbhoski\AppData\Local\Temp/cf15df1b-c29a-48fe-9dfa-365585f35248'); test_runner_cf15df1b_c29a_48fe_9dfa_365585f35248"'
Warning: Unable to locate a personal folder for $documents\MATLAB
[Warning: Unable to produce Cobertura model coverage. This problem might be due to a MATLAB release or operating system that does not support generating the
specified artifact, a missing toolbox, or a missing license.] 
[> In scriptgen.internal.sequences.test/CreateTestRunnerSequenceBuilder/buildPluginStatement (line 84)
  In scriptgen.internal.sequences.test/CreateTestRunnerSequenceBuilder/build (line 65)
  In scriptgen/CodeProvider/createCode (line 104)
  In scriptgen/CodeProvider/createSequence (line 67)
  In scriptgen.internal.scripts/TestScriptBuilder/build (line 43)
  In scriptgen/CodeProvider/createCode (line 104)
  In scriptgen/CodeProvider/createScript (line 72)
  In genscript (line 24)
  In test_runner_cf15df1b_c29a_48fe_9dfa_365585f35248 (line 1)] 
Running MATLAB script with content:
import matlab.unittest.TestRunner;
import matlab.unittest.Verbosity;
import matlab.unittest.plugins.TAPPlugin;
import matlab.unittest.plugins.ToFile;
import matlab.unittest.plugins.XMLPlugin;

addpath(genpath('C:\Nikhil\test\src'));
addpath(genpath('C:\Nikhil\test\test'));

suite = testsuite(pwd, 'IncludeSubfolders', true);

[~,~] = mkdir('new-coverage');
[~,~] = mkdir('new-results');

if exist(fullfile(pwd, 'new-results/results.tap'), 'file') == 2
    delete('new-results/results.tap');
end

runner = TestRunner.withTextOutput('OutputDetail', Verbosity.Detailed);
runner.addPlugin(TAPPlugin.producingVersion13(ToFile('new-results/results.tap')));
runner.addPlugin(XMLPlugin.producingJUnitFormat('new-results/results.xml'));
% Unable to produce Cobertura model coverage. This problem might be due to a MATLAB release or operating system that does not support generating the specified artifact, a missing toolbox, or a missing license.

results = runner.run(suite);

nfailed = nnz([results.Failed]);
assert(nfailed == 0, [num2str(nfailed) ' test(s) failed.']);
___________________________________

[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS

**Comment by nbhoski** [comment]
Hi @SangaviJayagopi  i used the same script and not able to reproduce the issue on my local. I could run my tests using src folder below is my script. (I made sure test folder was present in the workspace)

`pipeline {
agent any
environment {
PATH="C:\\Program Files\\MATLAB\\R2019b\\bin;${PATH}"
}

stages{
   stage('Run MATLAB Tests'){
        steps
        {
           runMATLABTests(
                           sourceFolder: ["C:\\Nikhil\\test\\src"],
                           testResultsTAP: 'new-results/results.tap',
                           testResultsJUnit: 'new-results/results.xml',
                           modelCoverageCobertura: 'new-coverage/coverage.xml')
        }  
    }
}        
} `
