### ISSUE TITLE
'functionbased tests' inside test folders not identified during Jenkins build nor show error in console/build

### ISSUE THREAD

**Issue by SangaviJayagopi** [mathworks/jenkins-matlab-plugin#181]
For testing the filter by Test folder, there is a sub-folder in https://github.com/mathworks/ci-test-repo/tree/master/test with function based tests inside.

They are function based tests and will not be recognized as a test entity.

Example,

$ matlab -batch "runtests('testMenu.m')";
Error using matlab.unittest.TestSuite.fromFile (line 187)
"testMenu" is not recognized as a test entity.

Error in testsuite>createSuite (line 189)
    suite = TestSuite.fromFile(file, selector);

Error in testsuite (line 128)
    suites{k} = createSuite(testAsChar, selector, ...

Error in runtests (line 98)
suites = testsuite(parseResults.TestsuiteInputs{:});

but the same is not seen at the end of Jenkins build where there are no console errors printed

**Comment by nbhoski** [comment]
Hi Sanghavi ,

May I request you to create a test suite before passing it to the runtests() directly. I guess its expected behavior when test suite is created and the test suite is run instead test is run directly. I am sure its Unit test framework's behaviour of skipping function base tests.

**Comment by SangaviJayagopi** [comment]
Nikhil,

I agree that this is an expected behavior of the function based tests when there is no test suite. I guess, my question is if Jenkins plugin is not recognizing such 'function based ' tests to throw the error in the console log.

**Comment by acampbel** [comment]
testMenu is not a valid function based test. See [here](https://www.mathworks.com/help/matlab/function-based-unit-tests.html) for how to define a function based tests, which specifically requires a certain format and structure

**Comment by acampbel** [comment]
Ah, I see you know this, but maybe we aren't using the same nomenclature. Also, it is part of the test framework to do test discovery when creating tests from a  folder.

This means that 

testsuite('testMenu.m') will error, because we specifically are trying to create a test suite from something that is not recognized as a test. However, when pointing to a folder, `testsuite` and `runtests` discover tests in that folder....and thus does not error out when it encounters files in that folder that are not tests. Also, it is valid to have an empty test suite from a folder (no tests inside that folder) just as it is valid to create a test suite from a valid matlab.unittest.TestCase or function based te=st that does not have any test procedures defined inside of it.

**Comment by SangaviJayagopi** [comment]
Thanks for that @acampbel

**Comment by acampbel** [comment]
👍👍 thank you!


Andy

[Sent from my phone]

On Jan 27, 2021, at 1:15 PM, SangaviJayagopi <notifications@github.com> wrote:

﻿

Thanks for that @acampbel<https://github.com/acampbel>
