### ISSUE TITLE
MATLAB steps configuration is lost when downgrading 2.13.2

### ISSUE THREAD

**Issue by Vahila** [mathworks/jenkins-matlab-plugin#333]
Reproduction steps:
1. Install 2.13.2 version
2. Create a project(Free or Matrix)
3. Downgrade the version to 2.13.1 or 2.13.0
Issue:
The MATLAB steps configuration is lost

**Comment by sameagen-MW** [comment]
Hey Vahila, that's expected behavior here because several datatypes that are serialized have been changed. Unfortunately, there's no way that I know of to make an older version of the plugin forward compatible. 

However, the upgrade should be backwards compatible, so if you create a project in 2.13.1 and upgrade it to 2.13.2 all configuration should remain identical.

Feel free to reach out to me for a call if you want to talk more about this issue!
